### ISSUE TITLE
Loops aren't optimized

### ISSUE THREAD

**Issue by valpackett** [weepy/kaffeine#24]
You have

```
for(_a = 0; _a < zoo.length; _a++)
```

instead of

```
for(_a = 0, l = zoo.length; _a < l; _a++)
```

which is faster and should be used everywhere.

**Comment by weepy** [comment]
Hey - fair point ... but, but it's only a tiny bit faster in the case where the loop does no work => so it's not _really_ faster in real world terms. It also introduces more complexity since we'd have to account for the extra variable.

If you really want to write this in kaffeine - you can just go right ahead an write it - but I don't plan to add this at the moment
